name: Bug Report
about: Create a report to help us improve
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: markdown
    id: reproduce
    value: |
      # Steps to reproduce the behavior:
        <!-- 1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error -->
  - type: markdown
    id: expected-behavior
    value: |
      # Expected behavior
      <!-- A clear and concise description of what you expect to happen. -->
  - type: textarea
    id: version
    attributes:
      label: Version
      description: |
         - OS: [e.g. iOS]
         - Browser [e.g. chrome, safari]
         - Version [e.g. 22]
    validations:
      required: true
  - type: textarea
    id: addition
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.
